### ISSUE TITLE
Show environment

### ISSUE THREAD

**Issue by seliardwb** [Jonur/pi-cucumber-reports#10]
This will be added to the JSON file like this:

`"environment":"Staging"`

**Comment by Jonur** [comment]
@seliardwb when you add this node to the JSON file, please upload a file sample here, as I don't even have the latest one with the "features" node.

**Comment by seliardwb** [comment]
@Jonur
Here's an example:
[cucumber.json.zip](https://github.com/Jonur/pi-cucumber-reports/files/2356805/cucumber.json.zip)

**Comment by Jonur** [comment]
Hi @seliardwb , this has been fixed. Feel free to `git pull`.
