### ISSUE TITLE
add screenshot links to the report

### ISSUE THREAD

**Issue by konstantinosmakris2** [Jonur/pi-cucumber-reports#15]
When a test step fails then there should be a link in the failed scenario. When the link is clicked then the image is displayed . The image is saved in "images" folder under targer folder in the project. The relative path is:  target/images/2018-09-25-17-32-56.jpeg. 
An example of a merged json file is attached
[cucumber.json.zip](https://github.com/Jonur/pi-cucumber-reports/files/2416150/cucumber.json.zip)

**Comment by Jonur** [comment]
Hello, @seliardwb , @konstantinosmakris2 , this is fixed. Please `git pull` and then `npm install`. The application is expecting the file path like this:

```
"after": [
            {
              "output": [
                "images/2018-09-25-17-32-56.jpeg"
              ],
```

So, it must be just "images" without the proceeding path, other indicators or a slash.
