### ISSUE TITLE
Add a button to switch projects

### ISSUE THREAD

**Issue by seliardwb** [Jonur/pi-cucumber-reports#5]

**Comment by Jonur** [comment]
As discussed, I will change the way the timer works and move it to Javascript, as now it is handled by the HTML with a `<meta http-equiv="refresh" content="30">`. The button will just be forcing the change. I will let you know when it's done! :heart:

**Comment by Jonur** [comment]
Hi @seliardwb , this is done. Now, also, you can add an endless amount of files, not just 2, and the project will be looping through them at the interval you chose to set at the `config.js`.
